# Generated by Django 6.1.1 on 2026-09-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_category_options"),
        ("inventory", "0003_alter_inventoryreservation_order"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="inventory",
            constraint=models.CheckConstraint(
                condition=models.Q(("reserved__lte", models.F("stock_on_hand"))),
                name="inventory_reserved_lte_stock",
            ),
        ),
    ]
