# Generated by Django 6.1.1 on 2026-09-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
        ("catalog", "0003_alter_category_options"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)), name="cart_item_quantity_positive"
            ),
        ),
    ]
