# Generated by Django 6.1.1 on 2026-10-02 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_cartitem_cart_item_quantity_positive"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "Active"), ("CONVERTED", "Converted")],
                default="ACTIVE",
                max_length=20,
            ),
        ),
    ]
