from django.core.exceptions import ValidationError as DjangoValidationError

from drf_spectacular.utils import (
    OpenApiExample,
    OpenApiParameter,
    OpenApiResponse,
    OpenApiTypes,
    extend_schema,
)

from rest_framework import status
from rest_framework.permissions import AllowAny, IsAuthenticated
from rest_framework.response import Response
from rest_framework.views import APIView

from apps.orders.models import Order

from .midtrans import MidtransAPIError, MidtransClient
from .models import Payment
from .notification_services import (
    process_payment_notification,
    process_payment_status,
)
from .serializers import (
    MidtransNotificationSerializer,
    PaymentCreateSerializer,
    PaymentSerializer,
)
from .services import create_payment


class PaymentCreateView(APIView):
    permission_classes = [IsAuthenticated]

    @extend_schema(
        operation_id="payments_create",
        summary="Create Payment",
        description="""
Create a payment for the authenticated user's pending order.

The request only contains the order number and selected payment method.
The backend is responsible for translating the selected payment method
into the appropriate Midtrans Core API charge payload.

\\### Supported payment methods

\\| Payment method | Midtrans method | Payment data returned |
\\|---|---|---|
\\| \\`BCA_VA\\` | Bank Transfer | \\`bank\\`, \\`va_number\\`, \\`expires_at\\` |
\\| \\`BNI_VA\\` | Bank Transfer | \\`bank\\`, \\`va_number\\`, \\`expires_at\\` |
\\| \\`BRI_VA\\` | Bank Transfer | \\`bank\\`, \\`va_number\\`, \\`expires_at\\` |
\\| \\`PERMATA_VA\\` | Bank Transfer | \\`bank\\`, \\`va_number\\`, \\`expires_at\\` |
\\| \\`CIMB_VA\\` | Bank Transfer | \\`bank\\`, \\`va_number\\`, \\`expires_at\\` |
\\| \\`MANDIRI\\` | E-Channel | \\`bill_key\\`, \\`biller_code\\`, \\`expires_at\\` |
\\| \\`GOPAY\\` | GoPay | \\`payment_url\\`, \\`expires_at\\` |
\\| \\`SHOPEEPAY\\` | ShopeePay | \\`payment_url\\`, \\`expires_at\\` |
\\| \\`QRIS\\` | QRIS | \\`qr_string\\` and/or \\`payment_url\\`, \\`expires_at\\` |

The frontend should inspect the returned payment fields based on the
selected \\`payment_method\\`.

For example:

\\- VA methods use \\`va_number\\`.
\\- \\`MANDIRI\\` uses \\`bill_key\\` and \\`biller_code\\`.
\\- \\`GOPAY\\` and \\`SHOPEEPAY\\` may use \\`payment_url\\`.
\\- \\`QRIS\\` may use \\`qr_string\\` and/or \\`payment_url\\`.

The payment is created in \\`PENDING\\` status. The actual payment status
is updated through the Midtrans notification webhook or through the
payment status sync endpoint.

This endpoint does not accept payment-specific fields such as
\\`va_number\\`, \\`bill_key\\`, \\`qr_string\\`, or \\`payment_url\\`. Those values are
generated by Midtrans and returned in the response.
""",
        request=PaymentCreateSerializer,
        responses={
            201: OpenApiResponse(
                response=PaymentSerializer,
                description="Payment successfully created.",
                examples=[
                    OpenApiExample(
                        "BCA Virtual Account",
                        value={
                            "id": 1,
                            "order_number": "GDR-20260930-0001",
                            "provider": "MIDTRANS",
                            "payment_method": "BCA_VA",
                            "status": "PENDING",
                            "transaction_id": "midtrans-transaction-001",
                            "amount": "515000.00",
                            "currency": "IDR",
                            "bank": "bca",
                            "va_number": "1234567890",
                            "bill_key": None,
                            "biller_code": None,
                            "qr_string": None,
                            "payment_url": None,
                            "paid_at": None,
                            "expires_at": "2026-10-01T15:30:00+07:00",
                            "created_at": "2026-10-01T14:30:00+07:00",
                        },
                        response_only=True,
                    ),
                    OpenApiExample(
                        "Mandiri Bill Payment",
                        value={
                            "id": 2,
                            "order_number": "GDR-20260930-0002",
                            "provider": "MIDTRANS",
                            "payment_method": "MANDIRI",
                            "status": "PENDING",
                            "transaction_id": "midtrans-transaction-002",
                            "amount": "750000.00",
                            "currency": "IDR",
                            "bank": None,
                            "va_number": None,
                            "bill_key": "123456789012",
                            "biller_code": "70012",
                            "qr_string": None,
                            "payment_url": None,
                            "paid_at": None,
                            "expires_at": "2026-10-01T15:30:00+07:00",
                            "created_at": "2026-10-01T14:30:00+07:00",
                        },
                        response_only=True,
                    ),
                    OpenApiExample(
                        "QRIS",
                        value={
                            "id": 3,
                            "order_number": "GDR-20260930-0003",
                            "provider": "MIDTRANS",
                            "payment_method": "QRIS",
                            "status": "PENDING",
                            "transaction_id": "midtrans-transaction-003",
                            "amount": "250000.00",
                            "currency": "IDR",
                            "bank": None,
                            "va_number": None,
                            "bill_key": None,
                            "biller_code": None,
                            "qr_string": "000201010212...",
                            "payment_url": "https://app.midtrans.com/snap/vtweb/...",
                            "paid_at": None,
                            "expires_at": "2026-10-01T15:30:00+07:00",
                            "created_at": "2026-10-01T14:30:00+07:00",
                        },
                        response_only=True,
                    ),
                ],
            ),
            400: OpenApiResponse(
                description="Invalid payment request or order state."
            ),
            401: OpenApiResponse(
                description="Authentication credentials were not provided."
            ),
            404: OpenApiResponse(
                description="Order not found for the authenticated user."
            ),
            502: OpenApiResponse(
                description="Midtrans API error."
            ),
        },
        examples=[
            OpenApiExample(
                "BCA Virtual Account Request",
                value={
                    "order_number": "GDR-20260930-0001",
                    "payment_method": "BCA_VA",
                },
                request_only=True,
            ),
            OpenApiExample(
                "Mandiri Request",
                value={
                    "order_number": "GDR-20260930-0002",
                    "payment_method": "MANDIRI",
                },
                request_only=True,
            ),
            OpenApiExample(
                "QRIS Request",
                value={
                    "order_number": "GDR-20260930-0003",
                    "payment_method": "QRIS",
                },
                request_only=True,
            ),
        ],
        tags=["Payments"],
    )
    def post(self, request):
        serializer = PaymentCreateSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)

        order_number = serializer.validated_data["order_number"]

        try:
            order = Order.objects.get(
                order_number=order_number,
                user=request.user,
            )
        except Order.DoesNotExist:
            return Response(
                {"detail": "Order not found."},
                status=status.HTTP_404_NOT_FOUND,
            )

        try:
            payment = create_payment(
                order=order,
                payment_method=serializer.validated_data["payment_method"],
            )
        except DjangoValidationError as exc:
            return Response(
                exc.message_dict,
                status=status.HTTP_400_BAD_REQUEST,
            )
        except MidtransAPIError as exc:
            return Response(
                {"detail": str(exc)},
                status=status.HTTP_502_BAD_GATEWAY,
            )

        return Response(
            PaymentSerializer(payment).data,
            status=status.HTTP_201_CREATED,
        )


class MidtransPaymentNotificationView(APIView):
    permission_classes = [AllowAny]
    authentication_classes = []

    @extend_schema(
        operation_id="payments_midtrans_notification",
        summary="Receive Midtrans Notification",
        description="""
Receive payment status notifications from Midtrans.

This endpoint is called by Midtrans and does not use JWT authentication.

The request signature is verified using the Midtrans signature formula:

\\`SHA512(order_id + status_code + gross_amount + ServerKey)\\`

The notification is processed idempotently. Terminal payment states
are not applied repeatedly.

Successful settlement/capture changes the payment to \\`PAID\\`, confirms
the order, confirms the inventory reservation, and creates the shipment.

Failed, denied, cancelled, or expired payments release the inventory
reservation and may cancel the order when the order is still pending.
""",
        request=MidtransNotificationSerializer,
        responses={
            200: OpenApiResponse(
                response=OpenApiTypes.OBJECT,
                description="Notification successfully processed.",
                examples=[
                    OpenApiExample(
                        "Success",
                        value={"status": "OK"},
                        response_only=True,
                    )
                ],
            ),
            400: OpenApiResponse(
                description="Invalid notification payload."
            ),
            403: OpenApiResponse(
                description="Invalid Midtrans signature."
            ),
            404: OpenApiResponse(
                description="Payment or order was not found."
            ),
        },
        examples=[
            OpenApiExample(
                "Settlement Notification",
                value={
                    "order_id": "GDR-20260930-0001",
                    "transaction_id": "midtrans-transaction-001",
                    "transaction_status": "settlement",
                    "status_code": "200",
                    "status_message": "Success, transaction is found",
                    "gross_amount": "515000.00",
                    "currency": "IDR",
                    "payment_type": "bank_transfer",
                    "fraud_status": "accept",
                    "signature_key": "generated-by-midtrans",
                    "bank": "bca",
                    "va_numbers": [
                        {
                            "bank": "bca",
                            "va_number": "1234567890",
                        }
                    ],
                },
                request_only=True,
            )
        ],
        tags=["Payments"],
    )
    def post(self, request):
        serializer = MidtransNotificationSerializer(
            data=request.data
        )
        serializer.is_valid(raise_exception=True)

        data = serializer.validated_data

        client = MidtransClient()

        if not client.verify_notification_signature(data):
            return Response(
                {"detail": "Invalid signature."},
                status=status.HTTP_403_FORBIDDEN,
            )

        try:
            process_payment_notification(
                payload=data,
            )
        except Payment.DoesNotExist:
            return Response(
                {"detail": "Payment not found."},
                status=status.HTTP_404_NOT_FOUND,
            )
        except DjangoValidationError as exc:
            return Response(
                exc.message_dict,
                status=status.HTTP_400_BAD_REQUEST,
            )

        return Response(
            {"status": "OK"},
            status=status.HTTP_200_OK,
        )


class PaymentStatusSyncView(APIView):
    permission_classes = [IsAuthenticated]

    @extend_schema(
        operation_id="payments_status_sync",
        summary="Sync Payment Status",
        description="""
Synchronize the payment status of an order with Midtrans.

This endpoint is a fallback reconciliation mechanism when a Midtrans
notification has not been received yet. It does not replace the
Midtrans notification webhook.

Only the authenticated owner of the order can perform this operation.
""",
        parameters=[
            OpenApiParameter(
                name="order_number",
                type=OpenApiTypes.STR,
                location=OpenApiParameter.PATH,
                description="GIDORA order number.",
                examples=[
                    OpenApiExample(
                        "Order Number",
                        value="GDR-20260930-0001",
                    )
                ],
            )
        ],
        request=None,
        responses={
            200: OpenApiResponse(
                response=PaymentSerializer,
                description="Payment status successfully synchronized.",
                examples=[
                    OpenApiExample(
                        "Payment Status",
                        value={
                            "id": 1,
                            "order_number": "GDR-20260930-0001",
                            "provider": "MIDTRANS",
                            "payment_method": "BCA_VA",
                            "status": "PAID",
                            "transaction_id": "midtrans-transaction-001",
                            "amount": "515000.00",
                            "currency": "IDR",
                            "bank": "bca",
                            "va_number": "1234567890",
                            "bill_key": None,
                            "biller_code": None,
                            "qr_string": None,
                            "payment_url": None,
                            "paid_at": "2026-10-01T14:45:00+07:00",
                            "expires_at": "2026-10-01T15:30:00+07:00",
                            "created_at": "2026-10-01T14:30:00+07:00",
                        },
                        response_only=True,
                    )
                ],
            ),
            400: OpenApiResponse(
                description="Payment status cannot be synchronized."
            ),
            401: OpenApiResponse(
                description="Authentication credentials were not provided."
            ),
            404: OpenApiResponse(
                description="Order or payment not found."
            ),
            502: OpenApiResponse(
                description="Midtrans API error."
            ),
        },
        tags=["Payments"],
    )
    def post(self, request, order_number):
        try:
            order = Order.objects.get(
                order_number=order_number,
                user=request.user,
            )
        except Order.DoesNotExist:
            return Response(
                {"detail": "Order or payment not found."},
                status=status.HTTP_404_NOT_FOUND,
            )

        try:
            payment = order.payment
        except Payment.DoesNotExist:
            return Response(
                {"detail": "Payment not found."},
                status=status.HTTP_404_NOT_FOUND,
            )

        try:
            client = MidtransClient()

            data = client.get_transaction_status(
                order.order_number,
            )

            process_payment_status(
                payload=data,
            )

            payment.refresh_from_db()

        except DjangoValidationError as exc:
            return Response(
                exc.message_dict,
                status=status.HTTP_400_BAD_REQUEST,
            )
        except MidtransAPIError as exc:
            return Response(
                {"detail": str(exc)},
                status=status.HTTP_502_BAD_GATEWAY,
            )

        return Response(
            PaymentSerializer(payment).data,
            status=status.HTTP_200_OK,
        )
