# Generated by Django 6.1.1 on 2026-09-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_shipping_courier_order_shipping_method_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderaddress",
            name="district",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderaddress",
            name="sub_district",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
