# Generated by Django 6.1.1 on 2026-09-19 15:46

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("OW", "Outerwear"),
                            ("PT", "Pants"),
                            ("SH", "Shirts"),
                            ("AC", "Accessories"),
                            ("FW", "Footwear"),
                        ],
                        editable=False,
                        max_length=2,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Code must contain only uppercase letters, numbers, and hyphens.",
                                regex="^[A-Z0-9]+(?:-[A-Z0-9]+)*$",
                            )
                        ],
                    ),
                ),
                ("next_product_sequence", models.PositiveIntegerField(default=1, editable=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Size",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["size_type", "sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="SizeType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("APPAREL", "Apparel"),
                            ("FOOTWEAR", "Footwear"),
                            ("ONE_SIZE", "One Size"),
                        ],
                        editable=False,
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("BLK", "Black"),
                            ("WHT", "White"),
                            ("GRY", "Gray"),
                            ("NVY", "Navy"),
                            ("OLV", "Olive"),
                            ("BGE", "Beige"),
                            ("PNK", "Pink"),
                        ],
                        editable=False,
                        max_length=3,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Code must contain only uppercase letters, numbers, and hyphens.",
                                regex="^[A-Z0-9]+(?:-[A-Z0-9]+)*$",
                            )
                        ],
                    ),
                ),
                ("slug", models.SlugField(editable=False, max_length=60, unique=True)),
                (
                    "hex_code",
                    models.CharField(
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Hex color must use format #RRGGBB.",
                                regex="^#[0-9A-Fa-f]{6}$",
                            )
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("name"), name="uq_color_name_ci"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("product_code", models.CharField(editable=False, max_length=30, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(editable=False, max_length=240, unique=True)),
                ("description", models.TextField(blank=True)),
                ("material", models.CharField(blank=True, max_length=200)),
                ("badge", models.CharField(blank=True, max_length=50)),
                (
                    "gender",
                    models.CharField(
                        choices=[("men", "Men"), ("women", "Women"), ("unisex", "Unisex")],
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="catalog.category",
                    ),
                ),
                (
                    "size_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="catalog.sizetype",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductColor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "color",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_colors",
                        to="catalog.color",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_colors",
                        to="catalog.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("image", models.URLField(max_length=500)),
                (
                    "image_type",
                    models.CharField(
                        choices=[
                            ("primary", "Primary"),
                            ("detail", "Detail"),
                            ("additional", "Additional"),
                        ],
                        max_length=20,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.product",
                    ),
                ),
                (
                    "product_color",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.productcolor",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sku", models.CharField(editable=False, max_length=80, unique=True)),
                ("price", models.DecimalField(decimal_places=0, max_digits=14)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "product_color",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="catalog.productcolor",
                    ),
                ),
                (
                    "size",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_variants",
                        to="catalog.size",
                    ),
                ),
            ],
            options={
                "ordering": ["size__sort_order", "size__name"],
            },
        ),
        migrations.AddField(
            model_name="size",
            name="size_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sizes",
                to="catalog.sizetype",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="default_size_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="default_categories",
                to="catalog.sizetype",
            ),
        ),
        migrations.AddConstraint(
            model_name="productcolor",
            constraint=models.UniqueConstraint(
                fields=("product", "color"), name="uq_product_color"
            ),
        ),
        migrations.AddConstraint(
            model_name="productimage",
            constraint=models.UniqueConstraint(
                fields=("product", "image_type", "sort_order"), name="uq_product_image_order"
            ),
        ),
        migrations.AddConstraint(
            model_name="productimage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("image_type", "primary"), ("product_color__isnull", True)),
                fields=("product",),
                name="uq_product_primary_image",
            ),
        ),
        migrations.AddConstraint(
            model_name="productimage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("image_type", "primary"), ("product_color__isnull", False)),
                fields=("product", "product_color"),
                name="uq_product_color_primary_image",
            ),
        ),
        migrations.AddConstraint(
            model_name="productvariant",
            constraint=models.UniqueConstraint(
                fields=("product_color", "size"), name="uq_product_variant_combination"
            ),
        ),
        migrations.AddConstraint(
            model_name="productvariant",
            constraint=models.CheckConstraint(
                condition=models.Q(("price__gte", 0)), name="ck_product_variant_price_gte_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="size",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("size_type"),
                name="uq_size_name_per_type_ci",
            ),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"), name="uq_category_name_ci"
            ),
        ),
        migrations.AddConstraint(
            model_name="category",
            constraint=models.CheckConstraint(
                condition=models.Q(("next_product_sequence__gte", 1)),
                name="ck_category_sequence_positive",
            ),
        ),
    ]
