# Generated by Django 6.1.1 on 2026-09-25 17:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="code",
            field=models.CharField(
                max_length=10,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Code must contain only uppercase letters, numbers, and hyphens.",
                        regex="^[A-Z0-9]+(?:-[A-Z0-9]+)*$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="color",
            name="code",
            field=models.CharField(
                max_length=10,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Code must contain only uppercase letters, numbers, and hyphens.",
                        regex="^[A-Z0-9]+(?:-[A-Z0-9]+)*$",
                    )
                ],
            ),
        ),
    ]
