# Generated by Django 6.1.1 on 2026-09-28 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_category_options"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="productimage",
            name="uq_product_image_order",
        ),
        migrations.RemoveConstraint(
            model_name="productimage",
            name="uq_product_primary_image",
        ),
        migrations.RemoveConstraint(
            model_name="productimage",
            name="uq_product_color_primary_image",
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(upload_to="products/"),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="product_color",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="catalog.productcolor",
            ),
        ),
        migrations.AddConstraint(
            model_name="productimage",
            constraint=models.UniqueConstraint(
                fields=("product_color", "image_type", "sort_order"),
                name="uq_product_color_image_order",
            ),
        ),
        migrations.AddConstraint(
            model_name="productimage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("image_type", "primary")),
                fields=("product_color",),
                name="uq_product_color_primary_image",
            ),
        ),
    ]
