# Generated by Django 6.1.1 on 2026-09-18 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={},
        ),
        migrations.RemoveConstraint(
            model_name="address",
            name="unique_default_address_per_user",
        ),
        migrations.RemoveField(
            model_name="address",
            name="is_default",
        ),
    ]
