# Generated by Django 6.1.1 on 2026-09-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_address_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="district",
            field=models.CharField(default="-", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="address",
            name="sub_district",
            field=models.CharField(default="-", max_length=100),
            preserve_default=False,
        ),
    ]
