# Generated by Django 6.1.1 on 2026-09-25 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0002_order_shipping_courier_order_shipping_method_code_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("MIDTRANS", "Midtrans")], default="MIDTRANS", max_length=20
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("BCA_VA", "BCA Virtual Account"),
                            ("BNI_VA", "BNI Virtual Account"),
                            ("BRI_VA", "BRI Virtual Account"),
                            ("MANDIRI", "Mandiri Bill"),
                            ("PERMATA_VA", "Permata Virtual Account"),
                            ("CIMB_VA", "CIMB Virtual Account"),
                            ("GOPAY", "GoPay"),
                            ("SHOPEEPAY", "ShopeePay"),
                            ("QRIS", "QRIS"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PAID", "Paid"),
                            ("FAILED", "Failed"),
                            ("EXPIRED", "Expired"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("transaction_id", models.CharField(blank=True, max_length=100)),
                ("amount", models.DecimalField(decimal_places=0, max_digits=14)),
                ("currency", models.CharField(default="IDR", max_length=3)),
                ("bank", models.CharField(blank=True, max_length=20)),
                ("va_number", models.CharField(blank=True, max_length=50)),
                ("bill_key", models.CharField(blank=True, max_length=50)),
                ("biller_code", models.CharField(blank=True, max_length=50)),
                ("qr_string", models.TextField(blank=True)),
                ("payment_url", models.URLField(blank=True, max_length=2048)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
